// The guards in shared/firestore.rules, for shared/proofs/mutate.mjs. Each entry loosens one:
// `from` is text that appears exactly once in the rules, `to` what it becomes, and `red`
// matches the name of the case in shared/rules-check.mjs that must then fail. A rules change
// adds its guards here with its cases.

export const GUARDS = [
  // ---- Rack It: one admin, everyone else a player (Sessions 6 and 6b) ----
  // ---- One admin (Session 9 step 4): no household tier ----
  { guard: "One admin: only the owner reaches sidequests/ beyond an app's own rules",
    from: "allow read, write: if isOwner() && !(appId in ['rack-it', 'sessions-loyalty']);",
    to: "allow read, write: if signedIn() && !(appId in ['rack-it', 'sessions-loyalty']);", red: /the household way|the other apps or the household people/ },
  { guard: "One admin: the owner's reach skips Rack It, whose live matches keep their chain",
    from: "allow read, write: if isOwner() && !(appId in ['rack-it', 'sessions-loyalty']);",
    to: "allow read, write: if isOwner() && !(appId in ['sessions-loyalty']);", red: /the owner's stale write/ },
  { guard: "One admin: the owner's reach skips Sessions Loyalty, whose entries are only voided",
    from: "allow read, write: if isOwner() && !(appId in ['rack-it', 'sessions-loyalty']);",
    to: "allow read, write: if isOwner() && !(appId in ['rack-it']);", red: /the owner rewriting an entry/ },
  { guard: "One admin: an account asks only for its own /members document",
    from: "allow get: if signedIn() && request.auth.token.email == email;", to: "allow get: if signedIn();",
    red: /someone else's/ },
  { guard: "One admin: only the owner lists or writes /members",
    from: "      allow read, write: if isOwner();\n    }\n\n    // The owner reaches", to: "      allow read, write: if signedIn();\n    }\n\n    // The owner reaches",
    red: /listing \/members|inviting/ },
  { guard: "Rack It: a match is read by its players or the owner",
    from: "allow read: if (signedIn() && (request.auth.uid in resource.data.get('uids', [])\n          || resource.data.get('scorer', '') == request.auth.uid)) || isOwner();",
    to: "allow read: if signedIn();", red: /a match you aren't in/ },
  { guard: "Rack It: only the owner lists ratings",
    from: "allow list: if isOwner();", to: "allow list: if signedIn();", red: /listing ratings/ },
  { guard: "Rack It: only the owner reaches starters",
    from: "match /sidequests/rack-it/starters/{id} {\n      allow read, write: if isOwner();",
    to: "match /sidequests/rack-it/starters/{id} {\n      allow read, write: if signedIn();", red: /starter/ },
  { guard: "Rack It: a player never changes who's in a match",
    from: "!keys.hasAny(['uids', 'by', 'playerA', 'playerB', 'names', 'scorer', 'venue'])\n", to: "!keys.hasAny(['scorer', 'venue'])\n", red: /changing uids or the players/ },
  { guard: "Rack It: rated only ever turns off",
    from: "        && ratedOnlyTurnsOff()\n        && (was.status == 'live' ? liveScore(keys)\n          : was.status == 'pending' && (now.status",
    to: "        && (was.status == 'live' ? liveScore(keys)\n          : was.status == 'pending' && (now.status", red: /turning a friendly into a rated match/ },
  { guard: "Scorer: rated only ever turns off",
    from: "        && ratedOnlyTurnsOff()\n        && (was.status == 'live' ? liveScore(keys)\n          : was.status == 'pending' && now.status",
    to: "        && (was.status == 'live' ? liveScore(keys)\n          : was.status == 'pending' && now.status", red: /the scorer turning a friendly/ },
  { guard: "Rack It: you don't confirm a match you ended",
    from: "(!rated(now) || (request.auth.uid != was.get('endedBy', request.auth.uid) && othersConfirmed()))",
    to: "(!rated(now) || othersConfirmed())", red: /confirming your own result/ },
  { guard: "Rack It: a rating moves only with a match still rated",
    from: "now.status == 'done' && rated(now) && pid in now.uids", to: "now.status == 'done' && pid in now.uids",
    red: /Withdraw or Not right batch/ },
  { guard: "Rack It: you start a match only against someone you're connected to",
    from: "(m.uids.size() == 1 || (m.uids.size() == 2 && connected(m.uids[0], m.uids[1])))", to: "true",
    red: /someone you aren't connected to/ },
  // ---- The open rule (Session 7): Zombie Dice and every app in openApps() ----
  { guard: "Open: only the app's record collection is open",
    from: "allow create: if isOpen(appId) && coll in openApps()[appId] && signedIn() && opens();",
    to: "allow create: if isOpen(appId) && signedIn() && opens();", red: /anything under an open app but its records|outside the four collections/ },
  { guard: "Open: a record is read by the accounts in it",
    from: "allow read: if isOpen(appId) && coll in openApps()[appId]\n        && signedIn() && request.auth.uid in resource.data.get('uids', []);",
    to: "allow read: if isOpen(appId) && coll in openApps()[appId]\n        && signedIn();", red: /a stranger reading, listing or changing/ },
  { guard: "Open: a record is changed by the accounts in it",
    from: "((request.auth.uid in resource.data.get('uids', []) && (keepsWho() || openClaim()))", to: "(((keepsWho() || openClaim()))",
    red: /a stranger reading, listing or changing/ },
  { guard: "Open: playing on never changes who's in it",
    from: "affectedKeys().hasAny(['uids', 'players', 'by'])", to: "affectedKeys().hasAny([])", red: /changing who's in it/ },
  { guard: "Open: only whoever started it deletes it",
    from: "&& resource.data.get('by', '') == request.auth.uid;", to: ";", red: /didn't start it deleting it/ },
  { guard: "Open: a new record is yours",
    from: "&& r.by == request.auth.uid\n", to: "\n", red: /as someone else, without yourself/ },
  { guard: "Open: a new record has you in it",
    from: "        && request.auth.uid in r.uids\n", to: "\n", red: /as someone else, without yourself/ },
  { guard: "Open: every other account in it is one of the players",
    from: "(r.uids[i] in r.players && connected(", to: "(true && connected(", red: /an account that isn't playing/ },
  { guard: "Open: you're connected to every other account in it",
    from: "connected(request.auth.uid, r.uids[i]))", to: "true)",
    red: /an account you aren't connected to/ },
  { guard: "Open: at most eight players",
    from: "r.players is list && r.players.size() <= 8", to: "r.players is list", red: /more than eight players/ },
  { guard: "Open: a new record names its players",
    from: "r.keys().hasAll(['players', 'names', 'uids', 'by'])", to: "r.keys().hasAll(['players', 'uids', 'by'])",
    red: /no names/ },
  { guard: "Open: Photo Coach is on the list",
    from: "'bloc-11': ['climbs'],\n               'photo-coach': ['photos', 'images', 'batches', 'reviews'] };", to: "'bloc-11': ['climbs'] };",
    red: /adds a photo and its image/ },
  { guard: "Open: Photo Coach's images are open",
    from: "['photos', 'images', 'batches', 'reviews']", to: "['photos', 'batches', 'reviews']",
    red: /adds a photo and its image/ },
  { guard: "Open: Bloc 11 is on the list",
    from: "'around-the-clock': ['games'], 'bloc-11': ['climbs'],", to: "'around-the-clock': ['games'],",
    red: /logs a climb for themselves or their guest/ },
  { guard: "Open: Around the Clock is on the list",
    from: "'zombie-dice': ['games'], 'around-the-clock': ['games'],", to: "'zombie-dice': ['games'],",
    red: /anyone signed in starts a game with a guest or a friend/ },
  // ---- The Game QR in an open app (Session 9 step 3) ----
  { guard: "Open seats: a game is got only while it's live",
    from: "&& resource.data.get('status', '') == 'live' && connected(request.auth.uid, resource.data.get('by', ''));\n      allow create",
    to: "&& connected(request.auth.uid, resource.data.get('by', ''));\n      allow create", red: /getting a finished one/ },
  { guard: "Open seats: a game is got only by a friend of its starter",
    from: "&& resource.data.get('status', '') == 'live' && connected(request.auth.uid, resource.data.get('by', ''));\n      allow create",
    to: "&& resource.data.get('status', '') == 'live';\n      allow create", red: /not connected to the starter/ },
  { guard: "Open seats: the joiner takes the seat for themselves",
    from: "return newcomer() == request.auth.uid && resource.data.get('status', '') == 'live' && openSwap()",
    to: "return resource.data.get('status', '') == 'live' && openSwap()", red: /or someone else's/ },
  { guard: "Open seats: only in a live game",
    from: "return newcomer() == request.auth.uid && resource.data.get('status', '') == 'live' && openSwap()",
    to: "return newcomer() == request.auth.uid && openSwap()", red: /a seat in a finished game/ },
  { guard: "Open seats: only from a friend of the starter",
    from: "&& openSwap()\n        && connected(request.auth.uid, resource.data.get('by', ''));",
    to: "&& openSwap();", red: /not connected to the starter/ },
  // ---- Claiming a guest: seatSwap() (Session 8 step 1) ----
  { guard: "Claim: only the starter claims, in Rack It",
    from: "return resource.data.get('by', '') == request.auth.uid && rackSwap()", to: "return rackSwap()",
    red: /a claim by anyone but the starter/ },
  { guard: "Claim: only for someone the starter is connected to, in Rack It",
    from: "rackSwap() && connected(request.auth.uid, newcomer())", to: "rackSwap()", red: /isn't connected to/ },
  { guard: "Claim: only for someone the starter is connected to, in the open rule",
    from: "openSwap() && connected(request.auth.uid, newcomer())", to: "openSwap()", red: /isn't connected to/ },
  { guard: "Claim: nothing else in a Rack It match changes",
    from: "now.diff(was).affectedKeys().hasOnly(['playerA', 'playerB', 'uids', '_updatedAt']) && gainsOnly(x)",
    to: "gainsOnly(x)", red: /changes anything else in a Rack It match/ },
  { guard: "Claim: uids gain exactly the newcomer",
    from: "&& request.resource.data.uids.removeAll([x]) == was;", to: ";", red: /uids gain someone other/ },
  { guard: "Claim: only a guest's seat, in Rack It",
    from: "((isGuest(was.playerA) && now.playerA == x", to: "((true && now.playerA == x", red: /a seat held by an account/ },
  { guard: "Claim: by and names stay, in the open rule",
    from: "return !now.diff(was).affectedKeys().hasAny(['by', 'names'])", to: "return true", red: /changes by or names/ },
  { guard: "Claim: one seat only, in the open rule",
    from: "&& now.players.removeAll([x]).size() == was.players.size() - 1", to: "", red: /changes by or names, two seats/ },
  { guard: "Claim: every other seat stays where it was, in the open rule",
    from: "return was.size() <= i || request.resource.data.players[i] == was[i]", to: "return true", red: /or another seat/ },
  { guard: "Claim: a claimed starter never overwrites a rating",
    from: "return resource == null && isGuest(from)", to: "return isGuest(from)", red: /a claimed starter over a rating that exists/ },
  { guard: "Claim: a claimed starter only for the friend the guest was claimed by",
    from: "data.get('claimedBy', '') == pid", to: "data.get('claimedBy', '') != ''", red: /a claimed starter over/ },
  { guard: "Claim: a claimed starter keeps the guest's number",
    from: "&& r.zargo == g.zargo && r.get('robustness', 0)", to: "&& r.get('robustness', 0)", red: /a claimed starter over/ },
  { guard: "Claim: a claimed starter keeps the guest's robustness",
    from: "r.get('robustness', 0) == g.get('robustness', 0)", to: "true", red: /a claimed starter over/ },
  // ---- Seats and the Game QR (Session 8 step 2) ----
  { guard: "Seat: a live match is got only by someone connected to its starter",
    from: "allow get: if signedIn() && resource.data.get('status', '') == 'live'\n        && connected(request.auth.uid, resource.data.get('by', ''));",
    to: "allow get: if signedIn() && resource.data.get('status', '') == 'live';", red: /whose starter you aren't connected to/ },
  { guard: "Seat: only a live match is got that way",
    from: "allow get: if signedIn() && resource.data.get('status', '') == 'live'\n", to: "allow get: if signedIn()\n",
    red: /reading a finished match that way/ },
  { guard: "Seat: you seat only yourself",
    from: "return newcomer() == request.auth.uid && resource.data.status == 'live' && rackSwap()",
    to: "return resource.data.status == 'live' && rackSwap()", red: /seating someone else/ },
  { guard: "Seat: only in a live match",
    from: "newcomer() == request.auth.uid && resource.data.status == 'live' && rackSwap()",
    to: "newcomer() == request.auth.uid && rackSwap()", red: /taking a seat in one/ },
  { guard: "Seat: only in a match whose starter you're connected to",
    from: "&& rackSwap()\n        && connected(request.auth.uid, resource.data.get('by', ''));", to: "&& rackSwap();",
    red: /whose starter you aren't connected to/ },
  // ---- Two phones, one match: the chain (Session 8 step 3) ----
  { guard: "Chain: a player's live score write is the next link",
    from: "return (myPhone(keys) || nextLink())\n", to: "return true\n", red: /a score write with no link|a stale link/ },
  { guard: "Chain: a link is built on the stored key",
    from: "&& now.get('was', null) == was.get('key', '')", to: "", red: /a stale link/ },
  { guard: "Chain: a link is one more than the stored n",
    from: "return now.get('n', -1) == was.get('n', 0) + 1", to: "return true", red: /a stale link/ },
  { guard: "Chain: a link has a key of its own",
    from: "&& now.get('key', '') != was.get('key', '');", to: ";", red: /keeps the stored key/ },
  { guard: "Chain: a presence write touches only your own phone",
    from: "request.resource.data.phones.diff(resource.data.get('phones', {})).affectedKeys().hasOnly([request.auth.uid]);",
    to: "request.resource.data.phones.size() >= 0;", red: /someone else's phone/ },
  { guard: "Chain: a presence write touches nothing but phones",
    from: "return keys.hasOnly(['phones', '_updatedAt'])\n", to: "return true\n", red: /or the score|no link/ },
  { guard: "Chain: the owner keeps to it too",
    from: "|| (isOwner() && ownerKeepsChain());", to: "|| isOwner();", red: /the owner's stale write/ },
  // ---- A scorer, and both sign (Session 8 step 4) ----
  { guard: "Scorer: never in uids", from: "&& m.uids is list && m.uids.size() <= 2 && !(request.auth.uid in m.uids)",
    to: "&& m.uids is list && m.uids.size() <= 3", red: /a scorer who is also in uids/ },
  { guard: "Scorer: connected to the first player", from: "(m.uids.size() < 1 || connected(request.auth.uid, m.uids[0]))", to: "true",
    red: /not connected to a player/ },
  { guard: "Scorer: connected to the second player", from: "(m.uids.size() < 2 || connected(request.auth.uid, m.uids[1]))", to: "true",
    red: /not connected to a player/ },
  { guard: "Scorer: starts it as themselves", from: "return m.get('scorer', '') == request.auth.uid && m.by == request.auth.uid && m.status == 'live'",
    to: "return m.get('scorer', '') == request.auth.uid && m.status == 'live'", red: /not connected to a player/ },
  { guard: "Scorer: starts it live", from: "&& m.by == request.auth.uid && m.status == 'live'\n", to: "&& m.by == request.auth.uid\n",
    red: /not connected to a player/ },
  { guard: "Scorer: starts it not ended", from: "'withdrawnBy', 'confirms'])\n        && (m.uids.size() < 1", to: "'withdrawnBy'])\n        && (m.uids.size() < 1",
    red: /not connected to a player/ },
  { guard: "Scorer: a player never names one", from: "'withdrawnBy', 'scorer', 'confirms', 'venue'])", to: "'withdrawnBy', 'venue'])", red: /a player naming a scorer/ },
  { guard: "Scorer: a player never makes themselves one later", from: "!keys.hasAny(['uids', 'by', 'playerA', 'playerB', 'names', 'scorer', 'venue'])\n",
    to: "!keys.hasAny(['uids', 'by', 'playerA', 'playerB', 'names', 'venue'])\n", red: /a player naming a scorer/ },
  { guard: "Scorer: never changes who's playing", from: "!keys.hasAny(['uids', 'by', 'playerA', 'playerB', 'names', 'scorer', 'confirms', 'venue'])",
    to: "!keys.hasAny(['venue'])", red: /the scorer changing who's playing|a player naming a scorer/ },
  { guard: "Scorer: only the match's scorer scores it", from: "|| (signedIn() && resource.data.get('scorer', '') == request.auth.uid && scorerScores())",
    to: "|| (signedIn() && scorerScores())", red: /a stranger reading it, scoring it/ },
  { guard: "Scorer: is read only by its scorer", from: "|| resource.data.get('scorer', '') == request.auth.uid)) || isOwner();",
    to: "|| true)) || isOwner();", red: /a stranger reading it/ },
  { guard: "Scorer: never confirms", from: "was.status == 'pending' && now.status == 'done' && !rated(now)\n",
    to: "was.status == 'pending' && now.status == 'done'\n", red: /the scorer confirming/ },
  { guard: "Scorer: withdraws only as themselves", from: "&& now.get('withdrawnBy', '') == request.auth.uid);", to: ");",
    red: /withdrawing in someone else's name/ },
  { guard: "Both sign: a confirm touches only confirms", from: "return keys.hasOnly(['confirms', '_updatedAt']) && request.auth.uid != resource.data.get('endedBy', request.auth.uid)",
    to: "return request.auth.uid != resource.data.get('endedBy', request.auth.uid)", red: /moving the score with it/ },
  { guard: "Both sign: not on a match you ended", from: "&& request.auth.uid != resource.data.get('endedBy', request.auth.uid)\n        && request.resource.data.confirms",
    to: "\n        && request.resource.data.confirms", red: /a match you ended/ },
  { guard: "Both sign: a confirm never removes one", from: "&& request.resource.data.confirms.keys().hasAll(was.keys())\n", to: "\n",
    red: /confirms naming anyone but the writer/ },
  { guard: "Both sign: a confirm names only the writer", from: ".confirms.diff(was).affectedKeys().hasOnly([request.auth.uid]);", to: ".confirms.size() >= 0;",
    red: /confirms naming anyone but the writer/ },
  { guard: "Both sign: every other player has confirmed first", from: "&& othersConfirmed()))));", to: "))));",
    red: /a player confirming twice/ },
  // ---- A table session (Session 10 step 4) ----
  { guard: "Table: a player never names the club on their own match", from: "'withdrawnBy', 'scorer', 'confirms', 'venue'])", to: "'withdrawnBy', 'scorer', 'confirms'])",
    red: /a player naming the club/ },
  { guard: "Table: only a scorer on the staff list names the club", from: "(m.venue == 'sessions' && isStaff())", to: "(m.venue == 'sessions')",
    red: /a scorer who isn't staff/ },
  { guard: "Table: the club is the only venue", from: "(m.venue == 'sessions' && isStaff())", to: "isStaff()",
    red: /any other venue/ },
  { guard: "Table: a player never changes the venue", from: "'names', 'scorer', 'venue'])\n", to: "'names', 'scorer'])\n",
    red: /the venue set, changed or dropped/ },
  { guard: "Table: the scorer never changes the venue", from: "'names', 'scorer', 'confirms', 'venue'])", to: "'names', 'scorer', 'confirms'])",
    red: /the venue set, changed or dropped/ },
  { guard: "Table: an entry's match is an id", from: "|| request.resource.data.match is string);", to: "|| true);",
    red: /an entry's match that isn't an id/ },
  // ---- A pending match expires (Session 10 step 5) ----
  { guard: "Expiry: only once a week is up", from: "&& resource.data.endedAt <= request.time.toMillis() - 7 * 24 * 3600 * 1000);", to: ");",
    red: /expired before the week is up/ },
  { guard: "Expiry: only on a friendly", from: "request.resource.data.expired == true && !rated(request.resource.data)", to: "request.resource.data.expired == true",
    red: /expired on a match that stays rated/ },
  { guard: "Expiry: a player's finish checks it", from: "              && expiresFairly(keys)\n", to: "\n",
    red: /expired before the week is up/ },
  { guard: "Expiry: the scorer's finish checks it", from: "            && expiresFairly(keys));", to: "            );",
    red: /expired before the week is up/ },
  // ---- A late scorer by Game QR (Session 10 step 5) ----
  { guard: "Late scorer: only on a live match", from: "return resource.data.status == 'live' && !('scorer' in resource.data)", to: "return !('scorer' in resource.data)",
    red: /isn't live/ },
  { guard: "Late scorer: not when it has one", from: "&& !('scorer' in resource.data)\n", to: "\n", red: /has a scorer already/ },
  { guard: "Late scorer: names themselves", from: "&& request.resource.data.get('scorer', '') == request.auth.uid\n        && !(request.auth.uid in resource.data.get('uids', []))",
    to: "&& !(request.auth.uid in resource.data.get('uids', []))", red: /naming someone else/ },
  { guard: "Late scorer: never a player", from: "        && !(request.auth.uid in resource.data.get('uids', []))\n        && request.resource.data.diff",
    to: "        && request.resource.data.diff", red: /a player making themselves the scorer/ },
  { guard: "Late scorer: nothing else changes on the way in",
    from: "        && request.resource.data.diff(resource.data).affectedKeys().hasOnly(['scorer', '_updatedAt'])\n        && connected(request.auth.uid, resource.data.get('by', ''));",
    to: "        && connected(request.auth.uid, resource.data.get('by', ''));", red: /changing anything else on the way in/ },
  { guard: "Late scorer: connected to the starter", from: "        && connected(request.auth.uid, resource.data.get('by', ''));\n    }\n    // A rating moves",
    to: "        && true;\n    }\n    // A rating moves", red: /not connected to the starter/ },
  // ---- A chain for turn games (Session 10 step 5) ----
  { guard: "Turn chain: a player's write is the next link", from: "((keepsWho() && openLink()) || openClaim())", to: "(keepsWho() || openClaim())",
    red: /a stale phone's write|leaves rev as it was/ },
  { guard: "Turn chain: the owner keeps it on a live record", from: "        && (resource.data.get('status', '') != 'live' || openLink());", to: ";",
    red: /the owner's stale phone on a live game/ },
  { guard: "Turn chain: presence needs no link", from: "|| myPhone(request.resource.data.diff(resource.data).affectedKeys()) || nextLink();", to: "|| nextLink();",
    red: /presence needs no link/ },
  { guard: "Turn chain: only records that carry rev", from: "return !('rev' in resource.data)\n        || myPhone", to: "return myPhone",
    red: /a game with no rev is as it was/ },
  // ---- Accounts (Session 1) ----
  { guard: "Accounts: profiles are got one at a time, never listed",
    from: "match /profiles/{uid} {\n      allow get: if signedIn();", to: "match /profiles/{uid} {\n      allow read: if signedIn();",
    red: /listing \/profiles/ },
  { guard: "Accounts: a friendship needs a code that hasn't expired",
    from: "&& invite(request.resource.data.via).expires > request.time;", to: ";", red: /expired code/ },
];
