// The guards in shared/firestore.rules, for shared/proofs/mutate.mjs. Each entry loosens one:
// `from` is text that appears exactly once in the rules, `to` what it becomes, and `red`
// matches the name of the case in shared/rules-check.mjs that must then fail. A rules change
// adds its guards here with its cases.

export const GUARDS = [
  // ---- Rack It: one admin, everyone else a player (Sessions 6 and 6b) ----
  { guard: "Rack It: the household rule skips it for reads",
    from: "allow read: if isFamily() && appId != 'rack-it';", to: "allow read: if isFamily();",
    red: /reading or listing a match she isn't in/ },
  { guard: "Rack It: the household rule skips it for writes",
    from: "allow write: if isFamily() && appId != 'rack-it';", to: "allow write: if isFamily();",
    red: /writing state\/main, a starter, or any rating/ },
  { guard: "Rack It: a match is read by its players or the owner",
    from: "allow read: if (signedIn() && request.auth.uid in resource.data.get('uids', [])) || isOwner();",
    to: "allow read: if signedIn();", red: /a match you aren't in/ },
  { guard: "Rack It: only the owner lists ratings",
    from: "allow list: if isOwner();", to: "allow list: if signedIn();", red: /listing ratings/ },
  { guard: "Rack It: only the owner reaches starters",
    from: "match /sidequests/rack-it/starters/{id} {\n      allow read, write: if isOwner();",
    to: "match /sidequests/rack-it/starters/{id} {\n      allow read, write: if isFamily();", red: /starter/ },
  { guard: "Rack It: a player never changes who's in a match",
    from: "!keys.hasAny(['uids', 'by', 'playerA', 'playerB', 'names'])", to: "true", red: /changing uids or the players/ },
  { guard: "Rack It: rated only ever turns off",
    from: "&& ratedOnlyTurnsOff()\n", to: "\n", red: /turning a friendly into a rated match/ },
  { guard: "Rack It: you don't confirm a match you ended",
    from: "request.auth.uid != was.get('endedBy', request.auth.uid)", to: "true", red: /confirming your own result/ },
  { guard: "Rack It: a rating moves only with a match still rated",
    from: "now.status == 'done' && rated(now) && pid in now.uids", to: "now.status == 'done' && pid in now.uids",
    red: /Withdraw or Not right batch/ },
  { guard: "Rack It: you start a match only against someone you're connected to",
    from: "(m.uids.size() == 1 || (m.uids.size() == 2 && connected(m.uids[0], m.uids[1])))", to: "true",
    red: /someone you aren't connected to/ },
  // ---- The open rule (Session 7): Zombie Dice and every app in openApps() ----
  { guard: "Open: the household rule skips an open app",
    from: "allow read: if isFamily() && appId != 'rack-it' && !isOpen(appId);", to: "allow read: if isFamily() && appId != 'rack-it';",
    red: /a household member who isn't the owner listing bare/ },
  { guard: "Open: only the app's record collection is open",
    from: "allow create: if isOpen(appId) && openApps()[appId] == coll && signedIn() && opens();",
    to: "allow create: if isOpen(appId) && signedIn() && opens();", red: /anything under an open app but its records/ },
  { guard: "Open: a record is read by the accounts in it",
    from: "allow read: if isOpen(appId) && openApps()[appId] == coll\n        && signedIn() && request.auth.uid in resource.data.get('uids', []);",
    to: "allow read: if isOpen(appId) && openApps()[appId] == coll\n        && signedIn();", red: /a stranger reading, listing or changing/ },
  { guard: "Open: a record is changed by the accounts in it",
    from: "&& request.auth.uid in resource.data.get('uids', []) && keepsWho();", to: "&& keepsWho();",
    red: /a stranger reading, listing or changing/ },
  { guard: "Open: playing on never changes who's in it",
    from: "affectedKeys().hasAny(['uids', 'players', 'by'])", to: "affectedKeys().hasAny([])", red: /changing who's in it/ },
  { guard: "Open: only whoever started it deletes it",
    from: "&& resource.data.get('by', '') == request.auth.uid;", to: ";", red: /didn't start it deleting it/ },
  { guard: "Open: a new record is yours",
    from: "&& r.by == request.auth.uid\n", to: "\n", red: /as someone else, without yourself/ },
  { guard: "Open: a new record has you in it",
    from: "        && request.auth.uid in r.uids\n", to: "\n", red: /as someone else, without yourself/ },
  { guard: "Open: every account in it is one of the players",
    from: "(r.uids[i] in r.players && (", to: "(true && (", red: /an account that isn't playing/ },
  { guard: "Open: you're connected to every other account in it",
    from: "(r.uids[i] == request.auth.uid || connected(request.auth.uid, r.uids[i]))", to: "true",
    red: /an account you aren't connected to/ },
  { guard: "Open: at most eight players",
    from: "r.players is list && r.players.size() <= 8", to: "r.players is list", red: /more than eight players/ },
  { guard: "Open: a new record names its players",
    from: "r.keys().hasAll(['players', 'names', 'uids', 'by'])", to: "r.keys().hasAll(['players', 'uids', 'by'])",
    red: /no names/ },
  { guard: "Open: the owner alone reaches the rest of an open app",
    from: "allow read, write: if isOpen(appId) && isOwner();", to: "allow read, write: if isOpen(appId) && isFamily();",
    red: /a household member who isn't the owner listing bare|anything under an open app/ },
  { guard: "Open: Around the Clock is on the list",
    from: "'zombie-dice': 'games', 'around-the-clock': 'games'", to: "'zombie-dice': 'games'",
    red: /anyone signed in starts a game with a guest or a friend/ },
  // ---- Accounts (Session 1) ----
  { guard: "Accounts: profiles are got one at a time, never listed",
    from: "match /profiles/{uid} {\n      allow get: if signedIn();", to: "match /profiles/{uid} {\n      allow read: if signedIn();",
    red: /listing \/profiles/ },
  { guard: "Accounts: a friendship needs a code that hasn't expired",
    from: "&& invite(request.resource.data.via).expires > request.time;", to: ";", red: /expired code/ },
];
