// The guards in shared/firestore.rules, for shared/proofs/mutate.mjs. Each entry loosens one:
// `from` is text that appears exactly once in the rules, `to` what it becomes, and `red`
// matches the name of the case in shared/rules-check.mjs that must then fail. A rules change
// adds its guards here with its cases.

export const GUARDS = [
  // ---- Rack It: one admin, everyone else a player (Sessions 6 and 6b) ----
  { guard: "Rack It: the household rule skips it for reads",
    from: "allow read: if isFamily() && appId != 'rack-it';", to: "allow read: if isFamily();",
    red: /reading or listing a match she isn't in/ },
  { guard: "Rack It: the household rule skips it for writes",
    from: "allow write: if isFamily() && appId != 'rack-it';", to: "allow write: if isFamily();",
    red: /writing state\/main, a starter, or any rating/ },
  { guard: "Rack It: a match is read by its players or the owner",
    from: "allow read: if (signedIn() && request.auth.uid in resource.data.get('uids', [])) || isOwner();",
    to: "allow read: if signedIn();", red: /a match you aren't in/ },
  { guard: "Rack It: only the owner lists ratings",
    from: "allow list: if isOwner();", to: "allow list: if signedIn();", red: /listing ratings/ },
  { guard: "Rack It: only the owner reaches starters",
    from: "match /sidequests/rack-it/starters/{id} {\n      allow read, write: if isOwner();",
    to: "match /sidequests/rack-it/starters/{id} {\n      allow read, write: if isFamily();", red: /starter/ },
  { guard: "Rack It: a player never changes who's in a match",
    from: "!keys.hasAny(['uids', 'by', 'playerA', 'playerB', 'names'])", to: "true", red: /changing uids or the players/ },
  { guard: "Rack It: rated only ever turns off",
    from: "&& ratedOnlyTurnsOff()\n", to: "\n", red: /turning a friendly into a rated match/ },
  { guard: "Rack It: you don't confirm a match you ended",
    from: "request.auth.uid != was.get('endedBy', request.auth.uid)", to: "true", red: /confirming your own result/ },
  { guard: "Rack It: a rating moves only with a match still rated",
    from: "now.status == 'done' && rated(now) && pid in now.uids", to: "now.status == 'done' && pid in now.uids",
    red: /Withdraw or Not right batch/ },
  { guard: "Rack It: you start a match only against someone you're connected to",
    from: "(m.uids.size() == 1 || (m.uids.size() == 2 && connected(m.uids[0], m.uids[1])))", to: "true",
    red: /someone you aren't connected to/ },
  // ---- The open rule (Session 7): Zombie Dice and every app in openApps() ----
  { guard: "Open: the household rule skips an open app",
    from: "allow read: if isFamily() && appId != 'rack-it' && !isOpen(appId);", to: "allow read: if isFamily() && appId != 'rack-it';",
    red: /a household member who isn't the owner listing bare/ },
  { guard: "Open: only the app's record collection is open",
    from: "allow create: if isOpen(appId) && openApps()[appId] == coll && signedIn() && opens();",
    to: "allow create: if isOpen(appId) && signedIn() && opens();", red: /anything under an open app but its records/ },
  { guard: "Open: a record is read by the accounts in it",
    from: "allow read: if isOpen(appId) && openApps()[appId] == coll\n        && signedIn() && request.auth.uid in resource.data.get('uids', []);",
    to: "allow read: if isOpen(appId) && openApps()[appId] == coll\n        && signedIn();", red: /a stranger reading, listing or changing/ },
  { guard: "Open: a record is changed by the accounts in it",
    from: "&& request.auth.uid in resource.data.get('uids', []) && keepsWho();", to: "&& keepsWho();",
    red: /a stranger reading, listing or changing/ },
  { guard: "Open: playing on never changes who's in it",
    from: "affectedKeys().hasAny(['uids', 'players', 'by'])", to: "affectedKeys().hasAny([])", red: /changing who's in it/ },
  { guard: "Open: only whoever started it deletes it",
    from: "&& resource.data.get('by', '') == request.auth.uid;", to: ";", red: /didn't start it deleting it/ },
  { guard: "Open: a new record is yours",
    from: "&& r.by == request.auth.uid\n", to: "\n", red: /as someone else, without yourself/ },
  { guard: "Open: a new record has you in it",
    from: "        && request.auth.uid in r.uids\n", to: "\n", red: /as someone else, without yourself/ },
  { guard: "Open: every account in it is one of the players",
    from: "(r.uids[i] in r.players && (", to: "(true && (", red: /an account that isn't playing/ },
  { guard: "Open: you're connected to every other account in it",
    from: "(r.uids[i] == request.auth.uid || connected(request.auth.uid, r.uids[i]))", to: "true",
    red: /an account you aren't connected to/ },
  { guard: "Open: at most eight players",
    from: "r.players is list && r.players.size() <= 8", to: "r.players is list", red: /more than eight players/ },
  { guard: "Open: a new record names its players",
    from: "r.keys().hasAll(['players', 'names', 'uids', 'by'])", to: "r.keys().hasAll(['players', 'uids', 'by'])",
    red: /no names/ },
  { guard: "Open: the owner alone reaches the rest of an open app",
    from: "allow read, write: if isOpen(appId) && isOwner();", to: "allow read, write: if isOpen(appId) && isFamily();",
    red: /a household member who isn't the owner listing bare|anything under an open app/ },
  { guard: "Open: Around the Clock is on the list",
    from: "'zombie-dice': 'games', 'around-the-clock': 'games'", to: "'zombie-dice': 'games'",
    red: /anyone signed in starts a game with a guest or a friend/ },
  // ---- Claiming a guest: seatSwap() (Session 8 step 1) ----
  { guard: "Claim: only the starter claims, in Rack It",
    from: "return resource.data.get('by', '') == request.auth.uid && rackSwap()", to: "return rackSwap()",
    red: /a claim by anyone but the starter/ },
  { guard: "Claim: only for someone the starter is connected to, in Rack It",
    from: "rackSwap() && connected(request.auth.uid, newcomer())", to: "rackSwap()", red: /isn't connected to/ },
  { guard: "Claim: only for someone the starter is connected to, in the open rule",
    from: "openSwap() && connected(request.auth.uid, newcomer())", to: "openSwap()", red: /isn't connected to/ },
  { guard: "Claim: nothing else in a Rack It match changes",
    from: "now.diff(was).affectedKeys().hasOnly(['playerA', 'playerB', 'uids', '_updatedAt']) && gainsOnly(x)",
    to: "gainsOnly(x)", red: /changes anything else in a Rack It match/ },
  { guard: "Claim: uids gain exactly the newcomer",
    from: "&& request.resource.data.uids.removeAll([x]) == was;", to: ";", red: /uids gain someone other/ },
  { guard: "Claim: only a guest's seat, in Rack It",
    from: "((isGuest(was.playerA) && now.playerA == x", to: "((true && now.playerA == x", red: /a seat held by an account/ },
  { guard: "Claim: by and names stay, in the open rule",
    from: "return !now.diff(was).affectedKeys().hasAny(['by', 'names'])", to: "return true", red: /changes by or names/ },
  { guard: "Claim: one seat only, in the open rule",
    from: "&& now.players.removeAll([x]).size() == was.players.size() - 1", to: "", red: /changes by or names, two seats/ },
  { guard: "Claim: every other seat stays where it was, in the open rule",
    from: "return was.size() <= i || request.resource.data.players[i] == was[i]", to: "return true", red: /or another seat/ },
  { guard: "Claim: a claimed starter never overwrites a rating",
    from: "return resource == null && isGuest(from)", to: "return isGuest(from)", red: /a claimed starter over a rating that exists/ },
  { guard: "Claim: a claimed starter only for the friend the guest was claimed by",
    from: "data.get('claimedBy', '') == pid", to: "data.get('claimedBy', '') != ''", red: /a claimed starter over/ },
  { guard: "Claim: a claimed starter keeps the guest's number",
    from: "&& r.zargo == g.zargo && r.get('robustness', 0)", to: "&& r.get('robustness', 0)", red: /a claimed starter over/ },
  { guard: "Claim: a claimed starter keeps the guest's robustness",
    from: "r.get('robustness', 0) == g.get('robustness', 0)", to: "true", red: /a claimed starter over/ },
  // ---- Seats and the Game QR (Session 8 step 2) ----
  { guard: "Seat: a live match is got only by someone connected to its starter",
    from: "allow get: if signedIn() && resource.data.get('status', '') == 'live'\n        && connected(request.auth.uid, resource.data.get('by', ''));",
    to: "allow get: if signedIn() && resource.data.get('status', '') == 'live';", red: /whose starter you aren't connected to/ },
  { guard: "Seat: only a live match is got that way",
    from: "allow get: if signedIn() && resource.data.get('status', '') == 'live'\n", to: "allow get: if signedIn()\n",
    red: /reading a finished match that way/ },
  { guard: "Seat: you seat only yourself",
    from: "return newcomer() == request.auth.uid && resource.data.status == 'live' && rackSwap()",
    to: "return resource.data.status == 'live' && rackSwap()", red: /seating someone else/ },
  { guard: "Seat: only in a live match",
    from: "newcomer() == request.auth.uid && resource.data.status == 'live' && rackSwap()",
    to: "newcomer() == request.auth.uid && rackSwap()", red: /taking a seat in one/ },
  { guard: "Seat: only in a match whose starter you're connected to",
    from: "&& rackSwap()\n        && connected(request.auth.uid, resource.data.get('by', ''));", to: "&& rackSwap();",
    red: /whose starter you aren't connected to/ },
  // ---- Accounts (Session 1) ----
  { guard: "Accounts: profiles are got one at a time, never listed",
    from: "match /profiles/{uid} {\n      allow get: if signedIn();", to: "match /profiles/{uid} {\n      allow read: if signedIn();",
    red: /listing \/profiles/ },
  { guard: "Accounts: a friendship needs a code that hasn't expired",
    from: "&& invite(request.resource.data.via).expires > request.time;", to: ";", red: /expired code/ },
];
